# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

after_success:
    - Rscript -e 'covr::codecov()'

before_install:
  - Rscript -e 'install.packages("rjson")'
  - Rscript -e 'install.packages("rlist")'
  - Rscript -e 'install.packages("caTools")'